### ISSUE TITLE
Override CKeditor styles

### ISSUE THREAD

**Issue by mesosa** [t3kit/subtheme_t3kit_template#3]
Provide a skeleton for being to override the CKeditor styles in a subtheme, here is some provided code snippets on how it can be done: 

```
<?php
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['subtheme_t3kit_pixelant_default']
= 'EXT:subtheme_t3kit_template/Resources/Private/Extensions/RTE/Default.yaml';
```

check folder structure of this repo:
https://github.com/pixelant/subtheme_t3kit_pixelant/tree/master/Resources/Private/Extensions/RTE

**Comment by AdvanceWM** [comment]
To set up a new ckeditor configuration in T3kit follow these steps. We presume that your subtheme is named subtheme_t3kit_client, where client = Client Name.

Put your custom Ckeditor YAML file in: EXT:subtheme_t3kit_client/Resources/Private/Extensions/RTE/Default.yaml

In EXT:subtheme_t3kit_client/Configuration/PageTS/tsconfig.txt add line:
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:subtheme_t3kit_client/Resources/Private/Extensions/RTE/PageTS/tsconfig.txt">

In a new file EXT:subtheme_t3kit_client/Resources/Private/Extensions/RTE/PageTS/tsconfig.txt put the lines:
# switching to Custom RTE configuration
RTE.default.preset = client_default 

Create a file EXT:subtheme_t3kit_client/ext_localconf.php and register the new RTE preset with:
<?php
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

$GLOBALS['TYPO3_CONF_VARS']['RTE']['Presets']['client_default']
    = 'EXT:subtheme_t3kit_client/Resources/Private/Extensions/RTE/Default.yaml';

Publish your changes and clear the caches.

**Comment by dmh** [comment]
https://github.com/t3kit/subtheme_t3kit_template/pull/9
